grafana:
  image: ${GRAFANA_IMAGE}
  container_name: grafana-${NETWORK}
  restart: unless-stopped
  environment:
    GF_SECURITY_ADMIN_USER: admin
    GF_SECURITY_ADMIN_PASSWORD: admin
  volumes:
    - ${MEMPOOL_BASE_DIR}/${NETWORK}/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
  ports:
    - "${HOST_BIND_PREFIX}${GRAFANA_HOST_PORT}:3000"
  depends_on:
    - prometheus
  networks:
    - ${MEMPOOL_NETWORK_NAME}
