mariadb-exporter:
  image: prom/mysqld-exporter
  container_name: mariadb-exporter-${NETWORK}
  restart: unless-stopped
  command:
    - /bin/sh
    - -c
    - |
      export DATA_SOURCE_NAME="$(cat /run/secrets/${MARIADB_EXPORTER_DSN_SECRET_NAME})";
      exec /bin/mysqld_exporter
  secrets:
    - source: ${MARIADB_EXPORTER_DSN_SECRET_NAME}
  depends_on:
    - database
  networks:
    - ${MEMPOOL_NETWORK_NAME}
