bitcoind:
  image: ${BITCOIND_IMAGE}
  container_name: bitcoind-${NETWORK}
  hostname: bitcoind
  restart: unless-stopped
  stop_grace_period: 1m
  volumes:
    - ${BITCOIN_DATA_DIR}:/home/bitcoin/.bitcoin
    - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf:rw
  command: >
    bitcoind -conf=/home/bitcoin/.bitcoin/bitcoin.conf
  ports:
    - "${HOST_BIND_PREFIX}${CORE_RPC_PORT}:${CORE_RPC_PORT}"
    - "${HOST_BIND_PREFIX}${P2P_PORT}:${P2P_PORT}"
  networks:
    - ${MEMPOOL_NETWORK_NAME}
