web:
  image: ${MEMPOOL_WEB_IMAGE}
  container_name: mempool-web-${NETWORK}
  restart: unless-stopped
  depends_on:
    - api
  environment:
    FRONTEND_HTTP_PORT: 8080
    BACKEND_MAINNET_HTTP_HOST: api
    BACKEND_MAINNET_HTTP_PORT: 8999
  ports:
    - "${HOST_BIND_PREFIX}${WEB_PORT}:8080"
  networks:
    - ${MEMPOOL_NETWORK_NAME}
