secrets:
  ${DB_PASSWORD_SECRET_NAME}:
    file: ${DB_PASSWORD_SECRET_FILE}
  ${DB_ROOT_PASSWORD_SECRET_NAME}:
    file: ${DB_ROOT_PASSWORD_SECRET_FILE}
  ${MARIADB_EXPORTER_DSN_SECRET_NAME}:
    file: ${MARIADB_EXPORTER_DSN_SECRET_FILE}
networks:
  ${MEMPOOL_NETWORK_NAME}:
    driver: bridge
